[build]
  command = "python -m flask run --host=0.0.0.0 --port=$PORT 2>&1"
  command = "python main.py runserver 0.0.0.0:$PORT"
  command = "export FLASK_APP=main.py && flask run --host=0.0.0.0 --port=$PORT 2>&1"
  command = "export FLASK_APP=main.py && python -m flask run --host=0.0.0.0 --port=$PORT 2>&1"
